### ISSUE TITLE
[BUG] AxGens Default slots

### ISSUE THREAD

**Issue by Murt204** [Artillex-Studios/Issues#18] opened 2024-10-16 22:53 UTC
### Description of the bug

Issue with default slot amount, if players default slots are 25, and you do /axgens slots add 30, there slots will be 5, but it should be 55

### Expected behaviour

starting alots: 25
added slots: 25
result: 25
expected: 50

### Steps to reproduce

when the player first joins, add gen slots to there total

### Which plugin is this issue with?

axgens

### Versions

1.20.4

**Comment by BenceX100** [comment] 2024-10-25 06:35
The latest version changes how slot limits work, it should behave like you expect now

**Comment by Murt204** [comment] 2024-10-25 06:37
Did you also fix permission not overriding default?

**Comment by BenceX100** [comment] 2024-12-30 15:57
Everything should work as intended, so I am closing this

**Closed by BenceX100** 2024-12-30 15:57 UTC
Labels: axgens, priority: LOW, bug: unconfirmed
